### ISSUE TITLE
Properly handle unsupported requests

### ISSUE THREAD

**Issue by KDercksen** [informagi/REL#19]
Implement responses for e.g. HEAD requests and improperly formatted POST requests.

**Comment by mickvanhulst** [comment]
Some input based on issue #18 

Error below may be fixed by not accepting a 'None' value as input.
![image](https://user-images.githubusercontent.com/12170287/80860223-9e620c00-8c66-11ea-8117-7e2b0b48282e.png)

Then there's two more that caught my attention, first of: "ConnectionResetError: [Errno 104] Connection reset by peer.", for which the following post seems related: https://stackoverflow.com/questions/20568216/python-handling-socket-error-errno-104-connection-reset-by-peer

Then finally there's the one below, not sure how to replicate that one.
![image](https://user-images.githubusercontent.com/12170287/80860055-9eadd780-8c65-11ea-81c3-7eb6cfb39abd.png)
