### ISSUE TITLE
Option to return the flair entity types in the response body

### ISSUE THREAD

**Issue by Chriskamphuis** [informagi/REL#4]
FLAIR labels the detected mentions with an entity type. We could return these "for free", instead of requiring an extra join against DBPedia / Wikidata.

**Comment by KDercksen** [comment]
If the API is still compatible with Gerbil while returning extra fields in the response, I would just make this the default to be honest. No reason to make this optional when the entity type is available anyway, at least in the case where the default NER from Flair is being used. I suppose a custom NER model might only do mention detection without types, but even in that case we could just return a standard `ENTITY` type or something similar.

I could add this if @hasibi / @mickvanhulst agree (and can tell me if extra fields matter for Gerbil)?

**Comment by mickvanhulst** [comment]
I would agree with this.

Next to changing the fields in our Python code, we would also need to change the Gerbil middleware. At the moment this is expecting a certain JSON response, so if we can make it so that it ignores the remainder of the unnecessary fields, we are already there :).

Would be nice if you could work on this @KDercksen !

**Comment by KDercksen** [comment]
I don't have rights to close the issue myself, but I think this is done :)
