### ISSUE TITLE
Efficiency issues

### ISSUE THREAD

**Issue by vardaan123** [informagi/REL#52]
I am following your tutorial to integrate the end-to-end Entity Linking in my code to link mentions in a large number of documents. I have created a single instance of `EntityDisambiguation` class. But I find that the code runs slower as the iterations progress. I profiled the code to find that the bottleneck is in the method `get_data_items()` where the embeddings are being updated (self.__update_embeddings). Is there any way in which I can speed up the entity linking?

**Comment by mickvanhulst** [comment]
Hi @vardaan123 ,

So you're saying that over time the model becomes slower? This is probably because the embeddings are being stored in memory, thus becoming slower when your memory is full.

What you could do is use the parameter `reset_embeddings` and that resets the embeddings every time you run `get_data_items()`. 

If that is insufficient, then please give us some more details, so that we can see if there is room for a new type of feature here :).

**Comment by vardaan123** [comment]
Thanks, setting reset_embeddings=True indeed helped in improving the speed.
