### ISSUE TITLE
Error in Google Colab

### ISSUE THREAD

**Issue by sebduncan** [informagi/REL#66]
Hello,

Here is my code:

`from REL.entity_disambiguation import EntityDisambiguation`
`base_url = "/content"`
`wiki_version = "wiki_2019"`
`config = {"mode": "eval","model_path": "ed-wiki-2019"  # model alias}`
`ed_model = EntityDisambiguation(base_url, wiki_version, config)`

I get the following error:
`OperationalError: unable to open database file`

Any idea?

Many thanks

**Comment by KDercksen** [comment]
Hi Sebastien,

Have you uploaded all the necessary files to Colab? This could be a permissions problem, I haven't tried running REL on Colab myself.

**Comment by sebastien-mcrae** [comment]
Hi again,
Yes I downloaded the generic files and the ED model 2019.

**Comment by KDercksen** [comment]
Can you verify that the SQLite files are at `/content/wiki_2019/generated/entity_word_embedding.db` and `/content/generic/common_drawl.db`?

**Comment by mickvanhulst** [comment]
Hi @sebastien-mcrae ,

The error indicates that the database file can't be found. I believe Google Colab allows for around 50GB of disk space and part of that is taken by default (probably default packages etc). Now the Wikipedia 2019 database is already 40GB, so I doubt you will be able to use Google Colab default storage. In the past, I have used Google Drive, it allows for the files to persist, so that you don't have to constantly upload the database files. Note that you will have to connect to Google Drive and thus your file path will have to be changed.

If you're certain you have downloaded everything correctly, then try running the command `!ls /content/` in your notebook and see if the required files, that @KDercksen mentioned, are there.

**Comment by mickvanhulst** [comment]
Closing this for now. Feel free to re-open if there are any related questions :).
