### ISSUE TITLE
Implement GET request handling for status badge

### ISSUE THREAD

**Issue by KDercksen** [informagi/REL#8]
Thinking about how to make the repository look nice, I came across [Uptime Robot](https://uptimerobot.com/). It can send a GET request to the API every 5+ minutes, and we can use that result to put a API status badge in the repository readme:

![image](https://user-images.githubusercontent.com/4490728/76514400-1fb3d400-6458-11ea-8dd9-b05787c41911.png)

(anything more fancy than a standard GET request is not free anymore... :disappointed: )

Would this be a nice addition? I could add it if people agree it looks nice. This would be separate from the CI build badge (#7).

**Comment by arjenpdevries** [comment]
I like the status idea!

What about https://prometheus.io
See also https://www.robustperception.io/blog

_Prometheus is an open-source systems monitoring and alerting toolkit originally built at SoundCloud. Since its inception in 2012, many companies and organizations have adopted Prometheus, and the project has a very active developer and user community. It is now a standalone open source project and maintained independently of any company._

**Comment by KDercksen** [comment]
Better options :) we could run Prometheus on Gem as well. Alternatively, I also see on https://shields.io/endpoint that you can implement your own JSON endpoint to create a badge! That would not require a separate application, just some extra handling in REL itself.

**Comment by KDercksen** [comment]
I will create a PR for the above commit once SSL is enabled on the API. The status badge will show up in the README. If REL is offline:

![image](https://user-images.githubusercontent.com/4490728/76846260-819d8080-6840-11ea-9771-30f252c5316f.png)

And if it is running:

![image](https://user-images.githubusercontent.com/4490728/76846321-9da12200-6840-11ea-8a1c-17e0610604bf.png)
